// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartWatching(arg1) {
  return window['go']['main']['App']['StartWatching'](arg1);
}

export function StopWatching() {
  return window['go']['main']['App']['StopWatching']();
}

export function SyncFile(arg1) {
  return window['go']['main']['App']['SyncFile'](arg1);
}

export function SyncLocalToRemote() {
  return window['go']['main']['App']['SyncLocalToRemote']();
}

export function SyncRemoteToLocal() {
  return window['go']['main']['App']['SyncRemoteToLocal']();
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}
