// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadSettings():Promise<main.Config>;

export function SaveSettings(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:number,arg6:number):Promise<void>;

export function SelectFolder():Promise<string>;

export function StartWatching(arg1:string):Promise<void>;

export function StopWatching():Promise<void>;

export function SyncFile(arg1:string):Promise<void>;

export function SyncLocalToRemote():Promise<void>;

export function SyncRemoteToLocal():Promise<void>;

export function TestConnection(arg1:string,arg2:string):Promise<void>;
